name: Build and Publish Docker Container

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

      
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: criscrafter/Fischer-Vertretung:latest
      
    - name: Upload bot.py artifact
      uses: actions/upload-artifact@v2
      with:
        name: bot.py
        path: ./bot.py
